---
abstract: 'Install the Map::Tube modules.'
author:
  - 'Michal Spacek <skim@cpan.org>'
build_requires:
  Encode: 0
  English: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.08
  Test::More: 0
  Test::NoWarnings: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.14'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-Map-Tube
no_index:
  directory:
    - inc
    - t
requires:
  Map::Tube: 2.69
  Map::Tube::Barcelona: 0.16
  Map::Tube::Berlin: 0.06
  Map::Tube::Bucharest: 0.03
  Map::Tube::Budapest: 0.01
  Map::Tube::Delhi: 0.27
  Map::Tube::Dnipropetrovsk: 0.02
  Map::Tube::Graph: 0.04
  Map::Tube::GraphViz: 0.02
  Map::Tube::Kazan: 0.02
  Map::Tube::Kharkiv: 0.03
  Map::Tube::Kiev: 0.03
  Map::Tube::London: 0.45
  Map::Tube::Minsk: 0.03
  Map::Tube::Moscow: 0.02
  Map::Tube::NYC: 0.12
  Map::Tube::Nanjing: 0.01
  Map::Tube::Novosibirsk: 0.01
  Map::Tube::Plugin::Graph: 0.07
  Map::Tube::Prague: 0.06
  Map::Tube::SaintPetersburg: 0.02
  Map::Tube::Samara: 0.01
  Map::Tube::Sofia: 0.04
  Map::Tube::Tbilisi: 0.02
  Map::Tube::Text::Table: 0.03
  Map::Tube::Tokyo: 0.13
  Map::Tube::Warsaw: 0.02
  Map::Tube::Yekaterinburg: 0.01
  perl: 5.6.0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Task-Map-Tube
  homepage: https://github.com/tupinek/Task-Map-Tube
  license: http://opensource.org/licenses/artistic-license-2.0.php
  repository: git://github.com/tupinek/Task-Map-Tube
version: '0.11'
