---
abstract: 'Install the Map::Tube modules.'
author:
  - 'Michal Spacek <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.08
  Test::More: 0
  Test::NoWarnings: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.14'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-Map-Tube
no_index:
  directory:
    - inc
    - t
requires:
  Map::Tube: 2.99
  Map::Tube::CLI: 0.06
  Map::Tube::Graph: 0.04
  Map::Tube::GraphViz: 0.06
  Map::Tube::Plugin::Formatter: 0.07
  Map::Tube::Plugin::FuzzyFind: 0.08
  Map::Tube::Plugin::Graph: 0.18
  Map::Tube::Text::Shortest: 0.01
  Map::Tube::Text::Table: 0.04
  Task::Map::Tube::Metro: 0.01
  Test::Map::Tube: 0.07
  perl: 5.6.0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Task-Map-Tube
  homepage: https://github.com/tupinek/Task-Map-Tube
  license: http://opensource.org/licenses/artistic-license-2.0.php
  repository: git://github.com/tupinek/Task-Map-Tube
version: '0.35'
